language: node_js
node_js:
- node
before_script:
  - npm install -g bower
  - bower install
env:
  global:
addons:
  ssh_known_hosts: s493274694.online.de
before_deploy:
  - openssl aes-256-cbc -K $encrypted_39769eb20937_key -iv $encrypted_39769eb20937_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
after_success:
- bash _scripts/deploy.sh
